
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: stewie
spec:
  hosts:
  - {name: master, address: 192.168.0.9, internalAddress: 192.168.0.9, user: root, password: "123"}
  - {name: node1, address: 192.168.0.10, internalAddress: 192.168.0.10, user: root, password: "123"}
  - {name: node2, address: 192.168.0.11, internalAddress: 192.168.0.11, user: root, password: "123"}
  roleGroups:
    etcd:
    - master
    - node1
    - node2
    control-plane: 
    - master
    - node1
    - node2
    worker:
    - master
    - node1
    - node2
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    internalLoadbalancer: haproxy # 如果想要高可用，但是没有负载均衡器的话，可以开启这个参数，做集群内部的负载均衡

    domain: lb.kubesphere.local # 访问Kubernetes API 的域名
    address: ""
    port: 6443
  kubernetes:
    version: v1.28.8
    clusterName: cluster.local # 定义集群的名字
    autoRenewCerts: true # 自动更新证书内容
    containerManager: docker # 修改容器管理器 # 默认是 containerd （如果你想用的话）
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.1.11.0/18 # 定义Pod通信的IP
    kubeServiceCIDR: 10.2.22.0/18 # 定义svc的服务IP
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: "registry.cn-beijing.aliyuncs.com"
    namespaceOverride: "kubesphereio" # 阿里云 kubesphere 官方 namespace
    registryMirrors: []
    insecureRegistries: []
  addons: []

